routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/web_admin.php';
require __DIR__ . '/web_client.php';

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [
        'id',
    ];

    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];


    public function location()
    {
        return $this->belongsTo(Location::class);
    }


    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }


    public function orderProducts()
    {
        return $this->hasMany(OrderProduct::class)
            ->orderBy('id');
    }


    public function status()
    {
        if ($this->status == 4) {
            return trans('app.canceled');
        } elseif ($this->status == 3) {
            return trans('app.completed');
        } elseif ($this->status == 2) {
            return trans('app.sent');
        } elseif ($this->status == 1) {
            return trans('app.accepted');
        } else {
            return trans('app.pending');
        }
    }


    public function statusColor()
    {
        if ($this->status == 4) {
            return 'danger';
        } elseif ($this->status == 3) {
            return 'success';
        } elseif ($this->status == 2) {
            return 'info';
        } elseif ($this->status == 1) {
            return 'info';
        } else {
            return 'warning';
        }
    }


    public function platform()
    {
        switch ($this->platform) {
            case 1:
                return 'Android';
                break;
            case 2:
                return 'iOS';
                break;
            default:
                return 'Web';
        }
    }


    public function language()
    {
        switch ($this->language) {
            case 1:
                return 'eng';
            default:
                return 'tkm';
        }
    }


    public function payment()
    {
        switch ($this->payment) {
            case 1:
                return trans('app.terminalPayment');
                break;
            case 2:
                return trans('app.onlinePayment');
                break;
            default:
                return trans('app.cashPayment');
        }
    }


    public function updatePrice()
    {
        $totalPrice = 0;
        foreach ($this->orderProducts as $product) {
            $totalPrice += $product->total_price;
        }
        $this->total_price = round($totalPrice, 1);
        $this->update();
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->validate([
            'q' => 'nullable|string|max:255',
            'platform' => 'nullable|integer|between:0,3',
            'language' => 'nullable|integer|between:0,2',
            'payment' => 'nullable|integer|between:0,3',
            'status' => 'nullable|integer|between:0,4',
        ]);
        $q = $request->q ?: null;
        $f_platform = $request->has('platform') ? $request->platform : null;
        $f_language = $request->has('language') ? $request->language : null;
        $f_payment = $request->has('payment') ? $request->payment : null;
        $f_status = $request->has('status') ? $request->status : null;

        $objs = Order::when($q, function ($query, $q) {
            return $query->where(function ($query) use ($q) {
                $query->orWhere('code', 'like', '%' . $q . '%');
                $query->orWhere('customer_name', 'like', '%' . $q . '%');
                $query->orWhere('customer_phone', 'like', '%' . $q . '%');
                $query->orWhere('customer_address', 'like', '%' . $q . '%');
                $query->orWhere('customer_note', 'like', '%' . $q . '%');
            });
        })
            ->when(isset($f_platform), function ($query) use ($f_platform) {
                return $query->where('platform', $f_platform);
            })
            ->when(isset($f_language), function ($query) use ($f_language) {
                return $query->where('language', $f_language);
            })
            ->when(isset($f_payment), function ($query) use ($f_payment) {
                return $query->where('payment', $f_payment);
            })
            ->when(isset($f_status), function ($query) use ($f_status) {
                return $query->where('status', $f_status);
            })
            ->orderBy('id', 'desc')
            ->with(['location.parent', 'customer'])
            ->withCount(['orderProducts'])
            ->paginate(50)
            ->withQueryString();

        return view('admin.order.index')
            ->with([
                'objs' => $objs,
            ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/OrderController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    //
}

resources/views/admin/order/filter.blade.php
<form action="{{ route('admin.orders.index') }}" class="row align-items-center g-2" role="search">
    <div class="col">
        <input class="form-control form-control-sm" type="search" name="q" placeholder="1234 Main St">
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-dark btn-sm"><i class="bi-search"></i></button>
    </div>
</form>

resources/views/admin/order/index.blade.php
@extends('admin.layouts.app')
@section('title')
    @lang('app.orders')
@endsection
@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div class="h4 mb-0">
            @lang('app.orders')
        </div>
        <div>
            @include('admin.order.filter')
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Code</th>
                <th scope="col" width="30%">Location</th>
                <th scope="col">Customer</th>
                <th scope="col">Price</th>
                <th scope="col">Status</th>
            </tr>
            </thead>
            <tbody>
            @foreach($objs as $obj)
                <tr>
                    <td>{{ $obj->id }}</td>
                    <td>
                        <a href="{{ route('admin.orders.show', $obj->id) }}" class="text-decoration-none">
                            <span class="font-monospace">{{ $obj->code }}</span>
                            <i class="bi-box-arrow-up-right"></i>
                        </a>
                        <div class="small text-secondary">
                            <img src="{{ asset('img/flag/' . $obj->language() . '.png') }}" alt="Language" height="12" class="mb-1">
                            {{ $obj->platform() }}
                        </div>
                    </td>
                    <td>
                        <div class="mb-1">
                            <i class="bi-geo-alt-fill text-secondary"></i>
                            @if($obj->location->parent_id)
                                {{ $obj->location->parent->getName() }},
                            @endif
                            {{ $obj->location->getName() }}
                        </div>
                        <div class="small">
                            <i class="bi-geo-fill text-secondary"></i> {{ $obj->customer_address }}
                        </div>
                        @if($obj->customer_note)
                            <div class="small">
                                <i class="bi-sticky-fill text-warning"></i> {{ $obj->customer_note }}
                            </div>
                        @endif
                    </td>
                    <td>
                        @if($obj->customer_id)
                            <div class="mb-1">
                                <i class="bi-person-square text-secondary"></i>
                                <a href="{{ route('admin.customers.show', $obj->customer_id) }}" class="text-decoration-none">
                                    {{ $obj->customer_name }}
                                    @if($obj->customer_name != $obj->customer->name)
                                        ({{ $obj->customer->name }})
                                    @endif
                                    <i class="bi-box-arrow-up-right"></i>
                                </a>
                            </div>
                        @else
                            <div class="mb-1">
                                <i class="bi-person-square text-secondary"></i>
                                {{ $obj->customer_name }}
                            </div>
                        @endif
                        <div>
                            <i class="bi-telephone-fill text-success"></i>
                            <a href="tel:+993{{ $obj->customer_phone }}" class="text-decoration-none">
                                +993 {{ $obj->customer_phone }}
                            </a>
                        </div>
                    </td>
                    <td>
                        <div class="fs-5 mb-1">
                            {{ number_format($obj->total_price, 2, '.', ' ') }}
                            <small>TMT</small>
                        </div>
                        <div class="text-danger fw-semibold">
                            <i class="bi-box-fill text-secondary"></i> {{ $obj->order_products_count }}
                        </div>
                    </td>
                    <td>
                        <div class="mb-1">
                            <span class="badge text-bg-{{ $obj->statusColor() }}">{{ $obj->status() }}</span>
                        </div>
                        <div>{{ $obj->payment() }}</div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection